export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, mergeModels, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAffiliates } from '../src/composables/affiliates';
export { useAuth, initAuth, getAuthUrl, removeAuthProvider, getLauncherRedirectUrl } from '../src/composables/auth';
export { useAvalara1099, FormRequestAttributes, FormRequestLinks, FormRequestData, FormRequestResponse, UseAvalara1099Options } from '../src/composables/avalara1099';
export { useCompactNumber } from '../src/composables/compact-number';
export { useCountries, useFormattedCountries, useSubdivisions, useUserCountry } from '../src/composables/country';
export { createDisplayNames, useDisplayNames } from '../src/composables/display-names';
export { DEFAULT_FEATURE_FLAGS, useFeatureFlags, saveFeatureFlags, ProjectDisplayMode, DarkColorTheme, NumberFlag, BooleanFlag, RadioFlag, FlagValue, FeatureFlag, AllFeatureFlags, PartialFeatureFlags } from '../src/composables/featureFlags';
export { useBaseFetch } from '../src/composables/fetch';
export { useGeneratedState, ProjectType, LoaderData, Country, Subdivision, GeneratedState } from '../src/composables/generated';
export { useImageUpload } from '../src/composables/image-upload';
export { useLoading, startLoading, stopLoading } from '../src/composables/loading';
export { useTheme, useCosmetics } from '../src/composables/nuxt-accessors';
export { useNativeRoute, useNativeRouter } from '../src/composables/nuxt-bugfest';
export { getArrayOrString } from '../src/composables/query';
export { useRouteId } from '../src/composables/route-params';
export { useClientTry } from '../src/composables/use-client-try';
export { useUser, initUser, initUserCollections, initUserFollows, initUserProjects, userCollectProject, userFollowProject, resendVerifyEmail, logout } from '../src/composables/user';
export { useNotificationRightwards } from '../src/composables/util';
export { useMountedValue } from '../src/composables/vue';
export { useCountryNames, countryCodeToName, countryCodeToFlag, formatTimestamp, formatPercent, defaultColors, getDefaultColor, intToRgba, analyticsSetToCSVString, processAnalytics, processAnalyticsByCountry, useFetchAllAnalytics } from '../src/utils/analytics';
export { fetchSegmented, asEncodedJsonArray } from '../src/utils/fetch-helpers';
export { getCurrencyIcon, getCurrencyColor, getBlockchainIcon, getBlockchainColor } from '../src/utils/finance-icons';
export { getProjectTypeMessage } from '../src/utils/i18n-project-type';
export { MURALPAY_RAILS, getAvailableRails, getRailsByType, getRailConfig, FieldType, FieldConfig, RailConfig } from '../src/utils/muralpay-rails';
export { isPermission } from '../src/utils/permissions';
export { reportProject, reportVersion, reportUser } from '../src/utils/report-helpers';
export { normalizeChildren } from '../src/utils/vue-children';
export { useVIntl } from '@vintl/vintl';
export { defineMessages, defineMessage } from '@formatjs/intl';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../../../node_modules/.pnpm/@pinia+nuxt@0.5.5_magicast@0.3.5_typescript@5.9.2_vue@3.5.18_typescript@5.9.2_/node_modules/@pinia/nuxt/dist/runtime/composables';
export { definePageMeta } from '../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/pages/runtime/composables';