// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/_internal/templates/doc/:template': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/_internal/templates/doc/[template]').default>>>>
    }
    '/_internal/templates/email/:template': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/_internal/templates/email/[template]').default>>>>
    }
    '/_internal/templates/email/dynamic': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/_internal/templates/email/dynamic.post').default>>>>
    }
    '/.well-known/change-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/routes/.well-known/change-password').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}