// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.5.5_magicast@0.3.5_typescript@5.9.2_vue@3.5.18_typescript@5.9.2_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@vintl+nuxt@1.9.2_@vue+compiler-core@3.5.18_magicast@0.3.5_rollup@4.46.2_typescript@5.9.2_vit_yzc5q66kutghm5e7nayla55pj4/node_modules/@vintl/nuxt/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../src/plugins/cosmetics")> &
  InjectionType<typeof import("../../src/plugins/dayjs.js")> &
  InjectionType<typeof import("../../src/plugins/error-handling")> &
  InjectionType<typeof import("../../src/plugins/floating-vue.js")> &
  InjectionType<typeof import("../../src/plugins/scroll.client.js")> &
  InjectionType<typeof import("../../src/plugins/shorthands.js")> &
  InjectionType<typeof import("../../src/plugins/tanstack")> &
  InjectionType<typeof import("../../src/plugins/theme/index")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.18.1_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@20.19.9_@vue+compiler-sfc@_3iiw5cqlngib35pp3gvxzsvasa/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'cosmetics' | 'theme'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
